# Mediciones de Cohesión social en perspectiva internacional

Este informe se basa en el documento de trabajo Conceptos y medición de cohesión social en proyectos internacionales de COES [@castillo_Conceptos_2021], en que se analizan cinco estudios internacionales que han operacionalizado distintas mediciones de cohesión social y, además, se incluye una propuesta de medición de cohesión social elaborada por un consejo asesor para el Ministerio de Desarrollo Social y Familia de Chile: 

1) Mapping Social Cohesion, realizado en Canadá en 1998;

2) Scanlon-Monash Index of Social Cohesion, realizado en Australia desde 2007 hasta el 2019;

3) Social Cohesion Radar, que compara la tendencia en la cohesión social de 34 países (27 de la Unión Europea y 7 naciones industrializadas de occidente) entre 1989 y 2012;

4) Civic Engagement and Social Cohesion Report, realizado en Estados Unidos en 2014;

5) ECOsociAL, que fue realizada en siete países de América Latina (México, Guatemala, Colombia, Brasil, Perú, Argentina y Chile) en 2007.

6) Consejo Asesor para la Cohesión Social, realizado en Chile durante el 2020.

Cada uno de estos estudios ha propuesto distintas definiciones de cohesión social, lo que ha implicado, a su vez, que se presenten distintas formas de operacionalización. Como resultado, se tienen distintas dimensiones, subdimensiones e indicadores que pretenden medir cohesión social. Algunas de estas dimensiones son comunes entre algunos estudios pero, en su mayoría, presentan amplias diferencias en su operacionalización, combinando indicadores que en algunos estudios se presentan como subdimensiones y en otros constituyen dimensiones. Además, las subdimensiones de distintos estudios en ocasiones se relacionan con dimensiones diferentes.

A continuación se elaborará un resumen comparativo de las distintas formas de operacionalización de mediciones de cohesión social, resaltando las similitudes y diferencias que se encuentran en cada uno de estos estudios. Las principales dimensiones  que se han podido identificar de manera transversal a los diferentes estudios son: 1) Sentido de pertenencia; 2) Confianza en las instituciones; 3) Percepción de justicia; 4) Participación política; 5) Foco en el bien común; 6) Confianza social; 7) Aceptación de la diversidad; 8) Redes sociales; 9) trato digno; 10) Satisfacción con la vida, felicidad y expectativas sobre el futuro; 11) Calidad de la convivencia social; y 12) Percepción de oportunidades y movilidad social.

## Sentido de pertenencia

La dimensión denominada Sentido de Pertenencia, que aparece en Scanlon-Monash Index of Social Cohesion y en el informe del Consejo de Cohesión Social es similar a la subdimensión de Adhesión a la nación presente en ECOsociAL y una subdimensión de Identificación con la nación presente en Social Cohesion Radar. Por un lado, en el primero de estos estudios, la dimensión hace referencia a indicadores como el sentimiento de pertenencia con el país, el orgullo que siente por el país y la importancia de mantener la forma de vida y las costumbres del país. Por otro lado, en el Consejo de Cohesión Social esta dimensión sigue la propuesta realizada por el Social Cohesion Radar, el cual apunta a un aspecto más amplio de la pertenencia del país bajo una dimensión denominada Conectividad (entre individuos e instituciones o país) y que combina aspectos como la identificación con el país, la confianza en instituciones y la percepción de justicia. En el caso de ECOsociAL, presentan una dimensión denominada Calidad de la convivencia política, en que incluyen la subdimensión de Adhesión a la nación, que hace referencia a indicadores como el sentimiento de orgullo por el país y si se debe priorizar la economía nacional, la cultura nacional y los intereses del país. En este sentido, tanto en el Consejo de Cohesión Social como en el Social Cohesion Radar, la subdimensión de identificación con el país, que posee indicadores sobre sentimientos de orgullo, identificación y apego que se siente por el país, es similar a la dimensión de Sentido de Pertenencia propuesta por el Scanlon-Monash Index of Social Cohesion, mientras que en ECOsociAL solo el indicador de orgullo por el país, de la subdimensión Adhesión a la nación, es similar a esta dimensión. Sin embargo, las otras dos subdimensiones propuestas en el Social Cohesion Radar y en el Consejo de Cohesión Social y las otras cuatro subdimensiones de ECOsociAL son diferentes a la dimensión Sentido de Pertenencia de Scanlon-Monash Index of Social Cohesion.

## Confianza en instituciones

La subdimensión denominada Confianza en instituciones está contenida en las dimensiones de Sentido de pertenencia del Consejo de Cohesión Social, de Conectividad en el Social Cohesion Radar y de Calidad de la convivencia política de ECOsociAL. Estas tres subdimensiones poseen indicadores similares sobre la confianza en el gobierno, la justicia o el parlamento, pero están presentes en dimensiones diferentes. Por un lado, el Consejo de Cohesión Social y el Social Cohesion Radar la agrupan en sus dimensiones de Sentido de pertenencia y de Conectividad, respectivamente, junto con dos subdimensiones de Identificación y Percepción de Justicia. Por otro lado, ECOsociAL agrupa su subdimensión de confianza en instituciones junto con las subdimensiones de Democracia y Derechos, Violencia y riesgo político, Distancia con las autoridades y Adhesión a la nación, dentro de la dimensión de Calidad de la convivencia política. La subdimensión de Democracia y Derechos, que agrupa indicadores de la calidad de integración institucional y de lealtad a la democracia, la subdimensión de Violencia y riesgo político, que agrupa indicadores de riesgo político observado y legitimación de la violencia y la subdimensión de Distancia con las autoridades, que agrupa indicadores de identificación y hostilidad hacia el gobierno, sólo están presentes en ECOsociAL.

## Percepción de justicia

La subdimensión de Percepción de justicia de la dimensión Conectividad de Social Cohesion Radar agrupa indicadores sobre corrupción, sobre si se recibe un sueldo justo y la opinión sobre si el gobierno debería reducir las diferencias en los niveles de ingresos. El Consejo de Cohesión Social incluye una subdimensión del mismo nombre en su dimensión Sentido de pertenencia, en la que utiliza indicadores de corrupción e incluye indicadores sobre la percepción de injusticia en el acceso a salud y educación, percepción de las diferencias de ingresos, si las personas son recompensadas por sus esfuerzos, la importancia del trabajo duro para surgir en la vida y si el gobierno toma en consideración el punto de vista de las personas para diseñar políticas públicas. Por un lado, los indicadores de percepción de injusticia en el acceso a salud y a educación es similar a las subdimensiones de Mapping Social Cohesion de Acceso a educación y capital humano y Acceso a la salud, que incluyen indicadores estructurales como la tasa de alfabetización, porcentaje de población que ha completado educación secundaria, la esperanza de vida al nacer o mortalidad infantil. Sin embargo, la dimensión de disparidades sociales de Mapping Social Cohesion también incluye otras subdimensiones sobre acceso a recursos financieros, acceso a tecnología y de inclusión en la actividad económica. Por otro lado, los indicadores de percepción de las diferencias de ingresos y de la importancia del trabajo duro para surgir en la vida de la subdimensión de Sentido de pertenencia del Consejo de Cohesión Social son similares a la dimensión de Equidad y justicia social de Scanlon-Monash Index of Social cohesion, en que se incluyen estos dos indicadores junto con la percepción de que las personas con bajos ingresos reciben suficiente apoyo y si el gobierno hace las cosas correctas por las personas.

## Participación política

Scanlon-Monash Index of Social Cohesion presenta una dimensión de Participación política, en que incluye indicadores sobre votar en elecciones, firmar una petición, asistir a una protesta o el contacto con miembros del parlamento. En Mapping Social Cohesion se presenta una subdimensión similar denominada Participación y solidaridad, en que se combinan indicadores sobre participación electoral, participación en asociaciones voluntarias y caridad. Asimismo, Social Cohesion Radar y el Consejo de Cohesión Social incluyen una subdimensión denominada Participación cívica, en que incluyen indicadores sobre participación en elecciones, interés en política, asistir a manifestaciones y trabajo en organizaciones sociales. En este sentido, si bien estas tres últimas subdimensiones son similares entre sí, están incluidas en dimensiones diferentes. La subdimensión de Participación y solidaridad de Mapping Social Cohesion se presenta en conjunto con una subdimensión de Confianza, en una dimensión denominada Mediciones de pertenencia y participación, mientras que la subdimensión de Participación cívica de Social Cohesion Radar y del Consejo de Cohesión Social se presenta junto a dos subdimensiones, una de Solidaridad y amabilidad, en la cual se incluye un indicador de trabajo en actividades de voluntariado y una de Respeto por las normas sociales, dentro de una dimensión denominada Foco en el bien común. 

## Foco en el bien común

En Social Cohesion Radar y en el Consejo de Cohesión social, dentro de su dimensión Foco en el bien común incluyen, por un lado, una subdimensión denominada Respeto por las normas sociales. En Social Cohesion Radar esta subdimensión incluye indicadores sobre cuán malo es cometer una infracción de tráfico, el tamaño de la economía informal y la sensación de seguridad caminando solo por la noche, mientras que en el Consejo de Cohesión Social esta subdimensión incluye un indicador de temor a caminar solo en la noche en su barrio y temor a ser acosado sexualmente en su lugar de trabajo o estudio. Por otro lado, Social Cohesion Radar incluye una subdimensión denominada Solidaridad y amabilidad, que incluye indicadores de ayuda a extraños, trabajo voluntario y dinero donado, mientras que en el Consejo de Cohesión Social esta subdimensión se denomina Solidaridad y ayuda e incluye indicadores de percepción sobre si el gobierno debería subir impuestos a los más ricos para ayudar a los pobres, disposición a pagar impuestos para mejorar atención en salud y indicadores de donar dinero y participar en actividades de voluntariado.

## Confianza social

Como se mencionó anteriormente, en Mapping Social Cohesion se presenta una dimensión de mediciones de pertenencia y participación, que posee una subdimensión de Confianza que incluye indicadores sobre confianza en las personas a partir de encuesta de opinión pública. Esta subdimensión es similar a la subdimensión de Confianza en las personas que presentan Social Cohesion Radar y el Consejo de Cohesión Social, que incluye indicadores sobre la confianza social generalizada, de percepción sobre si las personas intentan ser justas y sobre altruismo social y que se incluye en una dimensión denominada Calidad del vínculo social. De la misma forma, esta subdimensión es similar a la subdimensión de Confianza social presentada por ECOsociAL, que incluye indicadores sobre si se puede confiar en las personas y si la mayoría de las personas actúa correctamente, la que se incluye en una dimensión más amplia denominada Calidad de la convivencia social. Si bien estas subdimensiones son similares, nuevamente se presentan insertas en dimensiones distintas.

## Aceptación de la diversidad

En Scanlon Monash Index of Social Cohesion se propone una dimensión de Aceptación y rechazo, en que se incluyen indicadores de experiencias de discriminación en base a color de piel, etnia o religión, de pesimismo sobre el futuro, si cree que el gobierno debe dar asistencia para que las minorías étnicas mantengan sus costumbres y si cree que aceptar inmigrantes hace al país más fuerte. Por su parte, en Social cohesion radar se propone una subdimensión de Aceptación de la diversidad, que incluye indicadores de la percepción sobre si la cultura del país es socavada por los inmigrantes, si la ciudad es un buen lugar para minorías raciales o étnicas o para gays y lesbianas, si gays y lesbianas son libres de vivir su vida como deseen y la tensión religiosa existente. En el Consejo de Cohesión social se propone una subdimensión del mismo nombre, que incluye indicadores sobre percepción del aporte positivo y negativo de la migración, del derecho a casarse y de adopción de las parejas homosexuales y si se debe reconocer constitucionalmente a Chile como un país multicultural. En ECOsociAL se propone una subdimensión similar de Tolerancia y Discriminación, donde se incluyen indicadores de sentimientos de exclusión, como si lo que la persona piense no le importa a los demás, si lo dejan al margen de cosas que ocurren a su alrededor o si la gente haría poco para ayudarlo, un indicador de la frecuencia con que ha sido discriminado por color de piel, raza o etnia, religión, condición de pobreza o preferencia política, indicadores de tolerancia como situaciones en que sus hijos tienen un amigo homosexual, se casan con alguien de una clase social más baja o con alguien que no tiene religión, o sobre tener vecinos de una clase social más baja, inmigrantes o de otra raza, e indicadores sobre homogamia en relación con etnia, religión y educación. En el caso de Social Cohesion Radar y el Consejo de Cohesión social esta subdimensión se presenta dentro de la dimensión de Calidad del vínculo social, mientras que en ECOsociAL está dentro de la dimensión Calidad de la convivencia social. Finalmente, Mapping Social cohesion incluye una dimensión de homogeneidad cultural y étnica, en que incluyen indicadores del porcentaje de extranjeros en la población y de fraccionalización étnica. 

## Redes sociales

Dentro de la dimensión Calidad del vínculo social de Social Cohesion Radar se incluye una subdimensión de Redes sociales, que incluye indicadores sobre con qué frecuencia se reúne socialmente con amigos, familiares o colegas, cuánto tiempo durante la semana se sintió solo, si cuenta con ayuda y si cuenta con apoyo si necesita consejos. Esta subdimensión se presenta de manera similar en el Consejo de cohesión social bajo el nombre de Relaciones sociales, que posee indicadores sobre la cantidad de amistades cercanas, el contacto presencial con amistades y con vecinos y las redes de apoyo para obtener un préstamo y para conversar sobre temas importantes. En Civic Engagement and Social cohesion report se incluye una dimensión de nivel individual que posee indicadores sobre la presencia de redes de apoyo, de participación en grupos de chat online y de la frecuencia de interacción con familia o amigos, de las veces que ha recibido ayuda de familia o amigos y la frecuencia con que ha sentido soledad. Asimismo, en ECOsociAL se presenta una subdimensión denominada Relaciones de amistad, vecindad y asociatividad, que incluye indicadores de asociatividad a partir de participación en organizaciones sociales y relaciones de amistad y vecindad a partir del número de amigos y vecinos que se conocen por su nombre y la frecuencia de contactos con ellos.

## Trato digno

El Consejo de Cohesión Social, dentro de la dimensión de Calidad del vínculo social, incluye una subdimensión de Trato digno, que posee indicadores sobre las experiencias de haber recibido malos tratos en sus diversas expresiones y, específicamente, en los servicios de salud y en las oficinas del servicio público y la percepción de conflictividad percibida entre clases bajas y altas. 

## Satisfacción con la vida, felicidad y expectativas sobre el futuro.

En Scanlon-Monash Index of social cohesion se presenta una dimensión denominada valoración, que posee subdimensiones de satisfacción con la situación financiera y de felicidad en los últimos años, que incluyen indicadores de satisfacción con la situación económica y de satisfacción con la vida, felicidad y de expectativas sobre el futuro. 

## Calidad de la convivencia social.

Dentro de la dimensión Calidad de la convivencia social de ECOsociAL se presenta una subdimensión de solidaridad familiar, que incluye indicadores de la calidad de relación con la familia; una subdimensión de solidaridad intergeneracional, que posee indicadores de la relación padres-hijos;  una subdimensión de Calidad de la vida de barrio, que posee indicadores de vandalismo, robos y asaltos; una subdimensión de Victimización, que posee indicadores de reportes de victimización por robo y de intimidación con arma de fuego; y una subdimensión de Temor, que posee indicadores de declaraciones de temor para cuando se está solo en la casa o caminando por el barrio durante la noche. 

## Percepción de oportunidades y movilidad social.

ECOsociAL propone una dimensión de Percepción de oportunidades y movilidad social, que posee las siguientes subdimensiones: Percepción de oportunidades; identificación socioeconómica; oportunidades de vulnerabilidad; Movilidad social; Legitimación de diferencias socioeconómicas; y Desigualdad.
