---
editor_options:
  markdown:
    wrap: 72
---

# Dimensiones comunes entre los estudios internacionales e indicadores presentes en ELSOC

## Sentido de pertenencia

En ELSOC los indicadores que miden esta dimensión son los pertenecientes al concepto de Identidad nacional, del módulo de Sociabilidad Política, y que preguntan por el grado de acuerdo o en desacuerdo con las siguientes dos afirmaciones: 1) Me identifico con Chile; y 2) Me siento orgulloso de ser chileno/a. En relación con la primera afirmación, esta también ha sido utilizada por el Consejo de Cohesión social, mientras que la segunda afirmación ha sido utilizada por Scanlon-Monash Index of Social Cohesion.

## Confianza en instituciones.

En ELSOC los indicadores que miden esta dimensión se encuentran en el módulo Ciudadanía y Democracia, bajo el concepto de Confianza en instituciones que pregunta sobre el grado de confianza hacia 1) El congreso nacional; 2) Los partidos políticos; 3) Fiscalía Nacional; 4) El poder judicial; 5) Carabineros; 6) Fuerzas armadas; 7) El gobierno; 8) Su municipalidad; 9) Los sindicatos; 10) Las empresas privadas; 11) El presidente de la república; 12) Bomberos; y 13) Medios de comunicación tradicionales. De estos indicadores, los primeros seis han sido utilizados por Social Cohesion Radar y por el Consejo de cohesión social, mientras que los indicadores 7 y 8 han sido utilizados por ECOsociAL. Los últimos cinco indicadores no han sido utilizados en ningún estudio.

Además, dentro de esta dimensión se incluye una subdimensión de Lealtad hacia la democracia que, en ELSOC, el indicador que sirve para medir lealtad hacia la democracia se encuentra en el módulo de Ciudadanía y democracia, bajo el concepto de Actitud hacia la democracia, que pregunta sobre cuán satisfecho o insatisfecho se encuentra con el funcionamiento de la democracia en Chile. Este indicador específico no ha sido utilizado en ningún estudio previo. Sin embargo, ECOsociAL propone una subdimensión denominada Lealtad hacia la Democracia que pregunta si la democracia es mejor a cualquier otra forma de gobierno y si los derechos de las personas se deben respetar en toda circunstancia.

## Percepción de justicia

En ELSOC los indicadores que miden corrupción se encuentran en el módulo Ciudadanía y Democracia. El primero bajo el concepto de Anomia, que pregunta sobre el grado de acuerdo con que para que a uno le vaya bien en nuestro país, a veces es necesario hacer trampa y el segundo bajo el concepto de Percepción de corrupción, que pregunta sobre en qué medida la corrupción en la política está extendida en Chile. El primero de estos indicadores es utilizado en Social Cohesion Radar y el segundo es utilizado en el Consejo de cohesión social.

Los indicadores que miden si se recompensa el esfuerzo y la importancia del trabajo duro para surgir en la vida se encuentran en el módulo de Sociabilidad política, bajo el concepto de Justicia distributiva y meritocracia, que preguntan sobre el grado de acuerdo o en desacuerdo con que en Chile las personas son recompensadas por sus esfuerzos y por su inteligencia y habilidades. Estos dos indicadores han sido utilizados por el Consejo de cohesión social, mientras que indicadores similares han sido utilizados por Social Cohesion Radar, ECOsociAL y Scanlon-Monash Index of Social Cohesion. Otros indicadores presentes en ELSOC que podrían servir para medir esta subdimensión se encuentran en el módulo de Desigualdad y legitimidad, bajo el concepto de Surgir en la vida, y que preguntan sobre cuán importante es para surgir en la vida: 1) provenir de una familia rica o con muchos recursos; 2) tener un buen nivel de educación; 3) tener ambición; y 4) el trabajo duro.

Un indicador que mide la percepción de las diferencias de ingresos se encuentra en el módulo de Sociabilidad política, bajo el concepto de Desigualdad percibida, que pregunta sobre el grado de acuerdo o en desacuerdo con que en Chile las diferencias de ingresos son demasiado grandes. Otro indicador, que mide esta subdimensión se encuentra en el módulo Desigualdad y legitimidad, bajo el concepto de Conflicto de clase, que pregunta sobre cuán justa o injusta es la diferencia en la situación de vida entre las personas de clase alta y las de clase social baja en Chile. De estos indicadores solo el primero ha sido utilizado por el Consejo de Cohesión social, mientras que el segundo indicador presenta una versión similar en Scanlon-Monash Index of Social Cohesion, que pregunta por el grado de acuerdo con que existe una gran diferencia en ingresos. Asimismo, ELSOC presenta tres indicadores que podrían ser utilizados para medir esta subdimensión en el módulo de Sociabilidad política, bajo el concepto de Dominancia Social, que pregunta sobre el grado de acuerdo con las siguientes afirmaciones: 1) Una sociedad ideal requiere que algunos grupos estén en una posición superior y otros en una posición inferior; 2) Debiéramos trabajar para dar a todos los grupos la misma oportunidad de tener éxito; y 3) Deberíamos hacer todo lo posible por igualar las condiciones de diferentes grupos.

## Participación política

En ELSOC los principales indicadores que miden esta dimensión se encuentran en el módulo de Ciudadanía y Democracia, bajo el concepto de Participación ciudadana, que pregunta si votó en las últimas elecciones presidenciales, su grado de interés en la política y por la frecuencia con que 1) ha firmado una carta o petición; 2) Asistido a una marcha o manifestación pacífica; 3) participado en una huelga; 4) Usado las redes sociales para expresar su opinión en temas públicos; y 5) Participado en cacerolazos. Por un lado, el primer indicador sobre participación electoral está presente en Mapping Social Cohesion, Scanlon-Monash Index of Social Cohesion, Social Cohesion Radar y en el Consejo de Cohesión Social y el grado de interés en la política ha sido utilizado en Social Cohesion Radar y en el Consejo de Cohesión Social. Por otro lado, en cuanto a la frecuencia de participación ciudadana, el indicador sobre firmar una carta o petición ha sido utilizado por Scanlon-Monash Index of Social Cohesion y Social Cohesion Radar y el indicador sobre asistir a una marcha o manifestación ha sido utilizado por Scanlon-Monash Index of Social Cohesion y por el Consejo de cohesión social, mientras que los otros tres indicadores de frecuencia de participación ciudadana no se han utilizado en ninguno de los estudios revisados. En esta línea, el concepto de Participación ciudadana de ELSOC también incluye indicadores sobre la participación en las siguientes organizaciones voluntarias: 1) Juntas de vecinos u otra organización vecinal; 2) Organización religiosa; 3) Partido o movimiento político; 4) Sindicato; 5) Asociación profesional o gremial; 6) Organización deportiva; 7) Organización ecológica o medioambiental; y 7) asociaciones o centros de estudiantes. Este conjunto de organizaciones se agrupan en un solo indicador de Social Cohesion Radar y del Consejo de Cohesión Social que pregunta sobre la participación y trabajo en asociaciones u organizaciones sociales.

## Foco en el bien común

En ELSOC los indicadores que miden solidaridad se encuentran en el módulo Sociabilidad política y preguntan sobre la frecuencia con que 1) Ha hecho voluntariado y 2) ha donado dinero a una obra social o de caridad. Este primer indicador ha sido utilizado por Mapping Social Cohesion, Social Cohesion Radar y el Consejo de cohesión social, mientras que el segundo ha sido solo utilizado por Social Cohesion Radar y por el Consejo de Cohesión social. Asimismo, ELSOC incluye otros indicadores dentro del módulo Sociabilidad política que podrían ser útiles para medir esta subdimensión pero que no han sido utilizados por otras organizaciones. Estos abordan la frecuencia con que 1) Ha prestado una suma de dinero de $10.000.- o más; 2) Ha conversado con una persona en problemas o deprimida; y 3) Ha ayudado a alguien a conseguir trabajo.

## Confianza social

En ELSOC un indicador que mide esta dimensión es el perteneciente al concepto de Confianza en vecinos, del módulo Territorio, que aborda, en términos generales, cuánto confía la persona en sus vecinos, que es similar a los indicadores pertenecientes a Mapping Social Cohesion, Social Cohesion Radar y el Consejo de Cohesión Social. Otros indicadores son los pertenecientes al concepto de Confianza interpersonal, del módulo Ciudadanía y Democracia, que preguntan sobre 1) si la mayoría de las veces las personas tratan de ayudar a los demás o se preocupan mayormente solo de sí mismas; 2) si se puede confiar en la mayoría de las personas o hay que tener cuidado al tratar con ellas; y 3) si cree que la mayoría de la gente intentaría aprovecharse de usted si tuviera la oportunidad o cree que trataría de ser justa. El primer indicador ha sido utilizado en el Consejo de Cohesión social, mientras que los dos últimos han sido utilizados en 
ECOsociAL.

## Aceptación de la diversidad

Un indicador de ELSOC, que también ha sido utilizado por el Consejo de Cohesión Social, es el grado de acuerdo o en desacuerdo con que las parejas homosexuales deberían poder adoptar hijos. Existen otros indicadores de ELSOC que apuntan en una dirección similar a lo planteado en esta dimensión, pero que no han sido utilizados directamente por ninguna otra organización. Estos son el grado de acuerdo o en desacuerdo con que: 1) Chile debiera fomentar la migración de [peruanos/venezolanos] altamente calificados; 2) los migrantes [peruanos/venezolanos] deben tener el mismo acceso a los servicios de salud pública que los chilenos; 3) Es importante para mí que los peruanos que viven en Chile mantengan sus costumbres y tradiciones.; 4) Es importante para mí que los peruanos que viven en Chile adquieran la forma de vida de los chilenos; 5) Con la llegada de tantos peruanos, Chile está perdiendo su identidad; y 6)  Con la llegada de tantos peruanos a Chile está aumentando el desempleo.

## Redes sociales

En ELSOC el principal indicador que mide esta dimensión es el tamaño de la red cercana, presente en el módulo de Redes y Actitudes. Este indicador también está presente en ECOsociAL y en el Consejo de Cohesión Social.

## Trato digno

Los indicadores que miden la dimensión de Trato digno se encuentran en el módulo de Sociabilidad política. Un indicador, que también ha sido utilizado en el Consejo de Cohesión Social, corresponde a la frecuencia con que las personas son tratadas con respeto en los servicios de salud. Además, en este módulo se incluyen otros tres indicadores que no han sido utilizados en otro estudio y que preguntan sobre la frecuencia con que las personas son tratadas con respeto en el trabajo, por carabineros y por personas de clase alta.
El principal indicador que mide Tensión entre clases se encuentra en el módulo de Conflicto social, que pregunta sobre el conflicto percibido entre personas de clase alta y personas de clase baja. Un indicador similar ha sido utilizado por el Consejo de cohesión social, mientras que en Social Cohesion Radar se pregunta sobre la tensión entre ricos y pobres y en ECOsociAL se pregunta sobre la identificación y hostilidad con la clase baja, media y alta.

## Satisfacción con la vida, felicidad y expectativas sobre el futuro.

En ELSOC el indicador que mide esta dimensión se encuentra en el módulo Salud y Bienestar, que pregunta sobre el grado de satisfacción o insatisfacción con la vida en este momento. Este indicador también ha sido utilizado en Scanlon-Monash Index of Social Cohesion.

## Calidad de la convivencia social.

En ELSOC los indicadores que miden esta dimensión se encuentran dentro del módulo Territorio y preguntan sobre la frecuencia con que se han producido 1) robos o asaltos a personas, casas y/o vehículos; 2) riñas o peleas callejeras; 3) amenazas, insultos u ofensas de parte de vecinos de su barrio y 4) qué tan seguro o inseguro se siente en el barrio o vecindario en que la persona vive. Los tres primeros indicadores han sido utilizados por ECOsociAL, mientras que el cuarto ha sido utilizado por el Consejo de Cohesión Social. Asimismo, ELSOC incluye otros indicadores que podrían ser útiles para medir esta subdimensión pero que no han sido utilizados por otras organizaciones. Estos son indicadores de problemas de convivencia con los vecinos, de integración y pertenencia al vecindario y de satisfacción con el vecindario; todos ellos pertenecientes al módulo Territorio.

## Percepción de oportunidades y movilidad social.

En ELSOC un indicador que mide percepción de oportunidades se encuentra en el módulo Sociabilidad política, que pregunta sobre el grado de acuerdo o en desacuerdo con que en Chile las personas tienen igualdad de oportunidades para salir adelante. Si bien este indicador específico no ha sido utilizado en otro estudio, en ECOsociAL se pregunta sobre la percepción de oportunidades educativas y de bienestar.

Los indicadores que miden movilidad social se encuentran en el módulo Desigualdad y legitimidad bajo el concepto de Estatus subjetivo que, bajo la premisa de que en nuestra sociedad hay grupos que tienden a ubicarse en los niveles más altos y grupos que tienden a ubicarse en los niveles más bajos de la sociedad, pregunta sobre en qué posición se ubicaría en la sociedad chilena, dónde ubicaría la familia en la que creció y dónde cree que se ubicarán sus hijos. Tres indicadores similares han sido utilizados por ECOsociAL, que incluye la comparación del nivel educacional de los padres con el encuestado, la comparación entre su posición actual y hace diez años y la comparación entre el encuestado y sus hijos.